/* tslint:disable */
/* eslint-disable */
/**
 * xxx业务应用
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultListLkProductTypeMonthlyStatOutput } from '../models';
import { AdminResultLkUserInspectionStatOutput } from '../models';
/**
 * LkStatisticsApi - axios parameter creator
 * @export
 */
export const LkStatisticsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 按产品类型统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
         * @param {number} [year] 年份，例如 2025
         * @param {number} [month] 月份，1-12
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLkStatisticsMonthlyProductTypeStatGet: async (year?: number, month?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/lkStatistics/monthlyProductTypeStat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (year !== undefined) {
                localVarQueryParameter['Year'] = year;
            }

            if (month !== undefined) {
                localVarQueryParameter['Month'] = month;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 统计用户今日检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLkStatisticsUserTodayStatGet: async (userId?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/lkStatistics/userTodayStat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (userId !== undefined) {
                localVarQueryParameter['UserId'] = userId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 统计用户全量检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLkStatisticsUserTotalStatGet: async (userId?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/lkStatistics/userTotalStat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (userId !== undefined) {
                localVarQueryParameter['UserId'] = userId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LkStatisticsApi - functional programming interface
 * @export
 */
export const LkStatisticsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 按产品类型统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
         * @param {number} [year] 年份，例如 2025
         * @param {number} [month] 月份，1-12
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsMonthlyProductTypeStatGet(year?: number, month?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListLkProductTypeMonthlyStatOutput>>> {
            const localVarAxiosArgs = await LkStatisticsApiAxiosParamCreator(configuration).apiLkStatisticsMonthlyProductTypeStatGet(year, month, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 统计用户今日检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsUserTodayStatGet(userId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>>> {
            const localVarAxiosArgs = await LkStatisticsApiAxiosParamCreator(configuration).apiLkStatisticsUserTodayStatGet(userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 统计用户全量检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsUserTotalStatGet(userId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>>> {
            const localVarAxiosArgs = await LkStatisticsApiAxiosParamCreator(configuration).apiLkStatisticsUserTotalStatGet(userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * LkStatisticsApi - factory interface
 * @export
 */
export const LkStatisticsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 按产品类型统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
         * @param {number} [year] 年份，例如 2025
         * @param {number} [month] 月份，1-12
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsMonthlyProductTypeStatGet(year?: number, month?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListLkProductTypeMonthlyStatOutput>> {
            return LkStatisticsApiFp(configuration).apiLkStatisticsMonthlyProductTypeStatGet(year, month, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 统计用户今日检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsUserTodayStatGet(userId?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>> {
            return LkStatisticsApiFp(configuration).apiLkStatisticsUserTodayStatGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 统计用户全量检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsUserTotalStatGet(userId?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>> {
            return LkStatisticsApiFp(configuration).apiLkStatisticsUserTotalStatGet(userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LkStatisticsApi - object-oriented interface
 * @export
 * @class LkStatisticsApi
 * @extends {BaseAPI}
 */
export class LkStatisticsApi extends BaseAPI {
    /**
     * 
     * @summary 按产品类型统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
     * @param {number} [year] 年份，例如 2025
     * @param {number} [month] 月份，1-12
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsMonthlyProductTypeStatGet(year?: number, month?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListLkProductTypeMonthlyStatOutput>> {
        return LkStatisticsApiFp(this.configuration).apiLkStatisticsMonthlyProductTypeStatGet(year, month, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 统计用户今日检测情况（总数、OK 数、NG 数）🔖
     * @param {number} [userId] 用户ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsUserTodayStatGet(userId?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>> {
        return LkStatisticsApiFp(this.configuration).apiLkStatisticsUserTodayStatGet(userId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 统计用户全量检测情况（总数、OK 数、NG 数）🔖
     * @param {number} [userId] 用户ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsUserTotalStatGet(userId?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>> {
        return LkStatisticsApiFp(this.configuration).apiLkStatisticsUserTotalStatGet(userId, options).then((request) => request(this.axios, this.basePath));
    }
}
