/* tslint:disable */
/* eslint-disable */
/**
 * xxx业务应用
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultListLkProductTypeMonthlyStatOutput } from '../models';
import { AdminResultListLkProductTypeDailyStatOutput } from '../models';
import { AdminResultListLkUserMonthlyStatOutput } from '../models';
import { AdminResultListLkUserDailyStatOutput } from '../models';
import { AdminResultLkUserInspectionStatOutput } from '../models';
/**
 * LkStatisticsApi - axios parameter creator
 * @export
 */
export const LkStatisticsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 按人员统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
         * @param {number} [year] 年份，例如 2025
         * @param {number} [month] 月份，1-12
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLkStatisticsMonthlyUserStatGet: async (year?: number, month?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/lkStatistics/monthlyUserStat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (year !== undefined) {
                localVarQueryParameter['Year'] = year;
            }

            if (month !== undefined) {
                localVarQueryParameter['Month'] = month;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 按产品类型统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
         * @param {number} [year] 年份，例如 2025
         * @param {number} [month] 月份，1-12
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLkStatisticsMonthlyProductTypeStatGet: async (year?: number, month?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/lkStatistics/monthlyProductTypeStat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (year !== undefined) {
                localVarQueryParameter['Year'] = year;
            }

            if (month !== undefined) {
                localVarQueryParameter['Month'] = month;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 统计用户今日检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLkStatisticsUserTodayStatGet: async (userId?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/lkStatistics/userTodayStat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (userId !== undefined) {
                localVarQueryParameter['UserId'] = userId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 统计用户全量检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLkStatisticsUserTotalStatGet: async (userId?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/lkStatistics/userTotalStat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (userId !== undefined) {
                localVarQueryParameter['UserId'] = userId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * @summary 按人员统计每日检测汇总 🔖
         * @param {string} [date] 统计天起始日期 yyyy-MM-dd，不传时按 08:30 规则自动计算
         * @throws {RequiredError}
         */
        apiLkStatisticsDailyUserStatGet: async (date?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/lkStatistics/dailyUserStat`;
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) { baseOptions = configuration.baseOptions; }
            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken() : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            if (date !== undefined) { localVarQueryParameter['Date'] = date; }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) { query.set(key, localVarQueryParameter[key]); }
            for (const key in options.params) { query.set(key, options.params[key]); }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            const headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return { url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash, options: localVarRequestOptions };
        },
        /**
         * @summary 按产品类型统计每日检测汇总 🔖
         * @param {string} [date] 统计天起始日期 yyyy-MM-dd，不传时按 08:30 规则自动计算
         * @param {number} [productStatusId] 产品状态ID，不传时使用默认产品状态
         * @throws {RequiredError}
         */
        apiLkStatisticsDailyProductTypeStatGet: async (date?: string, productStatusId?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/lkStatistics/dailyProductTypeStat`;
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) { baseOptions = configuration.baseOptions; }
            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken() : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            if (date !== undefined) { localVarQueryParameter['Date'] = date; }
            if (productStatusId !== undefined) { localVarQueryParameter['ProductStatusId'] = productStatusId; }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) { query.set(key, localVarQueryParameter[key]); }
            for (const key in options.params) { query.set(key, options.params[key]); }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            const headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return { url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash, options: localVarRequestOptions };
        },
    }
};

/**
 * LkStatisticsApi - functional programming interface
 * @export
 */
export const LkStatisticsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 按人员统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
         * @param {number} [year] 年份，例如 2025
         * @param {number} [month] 月份，1-12
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsMonthlyUserStatGet(year?: number, month?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListLkUserMonthlyStatOutput>>> {
            const localVarAxiosArgs = await LkStatisticsApiAxiosParamCreator(configuration).apiLkStatisticsMonthlyUserStatGet(year, month, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 按产品类型统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
         * @param {number} [year] 年份，例如 2025
         * @param {number} [month] 月份，1-12
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsMonthlyProductTypeStatGet(year?: number, month?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListLkProductTypeMonthlyStatOutput>>> {
            const localVarAxiosArgs = await LkStatisticsApiAxiosParamCreator(configuration).apiLkStatisticsMonthlyProductTypeStatGet(year, month, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 统计用户今日检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsUserTodayStatGet(userId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>>> {
            const localVarAxiosArgs = await LkStatisticsApiAxiosParamCreator(configuration).apiLkStatisticsUserTodayStatGet(userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 统计用户全量检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsUserTotalStatGet(userId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>>> {
            const localVarAxiosArgs = await LkStatisticsApiAxiosParamCreator(configuration).apiLkStatisticsUserTotalStatGet(userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * @summary 按人员统计每日检测汇总 🔖
         */
        async apiLkStatisticsDailyUserStatGet(date?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListLkUserDailyStatOutput>>> {
            const localVarAxiosArgs = await LkStatisticsApiAxiosParamCreator(configuration).apiLkStatisticsDailyUserStatGet(date, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs: AxiosRequestConfig = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * @summary 按产品类型统计每日检测汇总 🔖
         */
        async apiLkStatisticsDailyProductTypeStatGet(date?: string, productStatusId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListLkProductTypeDailyStatOutput>>> {
            const localVarAxiosArgs = await LkStatisticsApiAxiosParamCreator(configuration).apiLkStatisticsDailyProductTypeStatGet(date, productStatusId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs: AxiosRequestConfig = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * LkStatisticsApi - factory interface
 * @export
 */
export const LkStatisticsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 按人员统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
         * @param {number} [year] 年份，例如 2025
         * @param {number} [month] 月份，1-12
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsMonthlyUserStatGet(year?: number, month?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListLkUserMonthlyStatOutput>> {
            return LkStatisticsApiFp(configuration).apiLkStatisticsMonthlyUserStatGet(year, month, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 按产品类型统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
         * @param {number} [year] 年份，例如 2025
         * @param {number} [month] 月份，1-12
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsMonthlyProductTypeStatGet(year?: number, month?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListLkProductTypeMonthlyStatOutput>> {
            return LkStatisticsApiFp(configuration).apiLkStatisticsMonthlyProductTypeStatGet(year, month, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 统计用户今日检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsUserTodayStatGet(userId?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>> {
            return LkStatisticsApiFp(configuration).apiLkStatisticsUserTodayStatGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 统计用户全量检测情况（总数、OK 数、NG 数）🔖
         * @param {number} [userId] 用户ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLkStatisticsUserTotalStatGet(userId?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>> {
            return LkStatisticsApiFp(configuration).apiLkStatisticsUserTotalStatGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * @summary 按人员统计每日检测汇总 🔖
         */
        async apiLkStatisticsDailyUserStatGet(date?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListLkUserDailyStatOutput>> {
            return LkStatisticsApiFp(configuration).apiLkStatisticsDailyUserStatGet(date, options).then((request) => request(axios, basePath));
        },
        /**
         * @summary 按产品类型统计每日检测汇总 🔖
         */
        async apiLkStatisticsDailyProductTypeStatGet(date?: string, productStatusId?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListLkProductTypeDailyStatOutput>> {
            return LkStatisticsApiFp(configuration).apiLkStatisticsDailyProductTypeStatGet(date, productStatusId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LkStatisticsApi - object-oriented interface
 * @export
 * @class LkStatisticsApi
 * @extends {BaseAPI}
 */
export class LkStatisticsApi extends BaseAPI {
    /**
     * 
     * @summary 按人员统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
     * @param {number} [year] 年份，例如 2025
     * @param {number} [month] 月份，1-12
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsMonthlyUserStatGet(year?: number, month?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListLkUserMonthlyStatOutput>> {
        return LkStatisticsApiFp(this.configuration).apiLkStatisticsMonthlyUserStatGet(year, month, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 按产品类型统计指定年月的检测总数、OK 数、NG 数及合格率 🔖
     * @param {number} [year] 年份，例如 2025
     * @param {number} [month] 月份，1-12
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsMonthlyProductTypeStatGet(year?: number, month?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListLkProductTypeMonthlyStatOutput>> {
        return LkStatisticsApiFp(this.configuration).apiLkStatisticsMonthlyProductTypeStatGet(year, month, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 统计用户今日检测情况（总数、OK 数、NG 数）🔖
     * @param {number} [userId] 用户ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsUserTodayStatGet(userId?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>> {
        return LkStatisticsApiFp(this.configuration).apiLkStatisticsUserTodayStatGet(userId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 统计用户全量检测情况（总数、OK 数、NG 数）🔖
     * @param {number} [userId] 用户ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsUserTotalStatGet(userId?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultLkUserInspectionStatOutput>> {
        return LkStatisticsApiFp(this.configuration).apiLkStatisticsUserTotalStatGet(userId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * @summary 按人员统计每日检测汇总 🔖
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsDailyUserStatGet(date?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListLkUserDailyStatOutput>> {
        return LkStatisticsApiFp(this.configuration).apiLkStatisticsDailyUserStatGet(date, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * @summary 按产品类型统计每日检测汇总 🔖
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsDailyProductTypeStatGet(date?: string, productStatusId?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListLkProductTypeDailyStatOutput>> {
        return LkStatisticsApiFp(this.configuration).apiLkStatisticsDailyProductTypeStatGet(date, productStatusId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * @summary 导出按人员月度检测统计 🔖
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsExportMonthlyUserStatPost(year: number, month: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Blob>> {
        const localVarPath = `/api/lkStatistics/exportMonthlyUserStat`;
        const localVarUrlObj = new URL(localVarPath, 'https://example.com');
        let baseOptions: any;
        if (this.configuration) { baseOptions = this.configuration.baseOptions; }
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', responseType: 'blob', ...baseOptions, ...options };
        const localVarHeaderParameter: any = {};
        if (this.configuration?.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? await this.configuration.accessToken() : await this.configuration.accessToken;
            localVarHeaderParameter['Authorization'] = 'Bearer ' + accessToken;
        }
        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = JSON.stringify({ year, month });
        return this.axios.request({ ...localVarRequestOptions, url: this.basePath + localVarUrlObj.pathname });
    }
    /**
     * @summary 导出按产品类型月度检测统计 🔖
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsExportMonthlyProductTypeStatPost(year: number, month: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Blob>> {
        const localVarPath = `/api/lkStatistics/exportMonthlyProductTypeStat`;
        const localVarUrlObj = new URL(localVarPath, 'https://example.com');
        let baseOptions: any;
        if (this.configuration) { baseOptions = this.configuration.baseOptions; }
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', responseType: 'blob', ...baseOptions, ...options };
        const localVarHeaderParameter: any = {};
        if (this.configuration?.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? await this.configuration.accessToken() : await this.configuration.accessToken;
            localVarHeaderParameter['Authorization'] = 'Bearer ' + accessToken;
        }
        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = JSON.stringify({ year, month });
        return this.axios.request({ ...localVarRequestOptions, url: this.basePath + localVarUrlObj.pathname });
    }
    /**
     * @summary 导出按人员每日检测统计 🔖
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsExportDailyUserStatPost(date?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Blob>> {
        const localVarPath = `/api/lkStatistics/exportDailyUserStat`;
        const localVarUrlObj = new URL(localVarPath, 'https://example.com');
        let baseOptions: any;
        if (this.configuration) { baseOptions = this.configuration.baseOptions; }
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', responseType: 'blob', ...baseOptions, ...options };
        const localVarHeaderParameter: any = {};
        if (this.configuration?.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? await this.configuration.accessToken() : await this.configuration.accessToken;
            localVarHeaderParameter['Authorization'] = 'Bearer ' + accessToken;
        }
        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = JSON.stringify({ date });
        return this.axios.request({ ...localVarRequestOptions, url: this.basePath + localVarUrlObj.pathname });
    }
    /**
     * @summary 导出按产品类型每日检测统计 🔖
     * @memberof LkStatisticsApi
     */
    public async apiLkStatisticsExportDailyProductTypeStatPost(date?: string, productStatusId?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Blob>> {
        const localVarPath = `/api/lkStatistics/exportDailyProductTypeStat`;
        const localVarUrlObj = new URL(localVarPath, 'https://example.com');
        let baseOptions: any;
        if (this.configuration) { baseOptions = this.configuration.baseOptions; }
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', responseType: 'blob', ...baseOptions, ...options };
        const localVarHeaderParameter: any = {};
        if (this.configuration?.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? await this.configuration.accessToken() : await this.configuration.accessToken;
            localVarHeaderParameter['Authorization'] = 'Bearer ' + accessToken;
        }
        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = JSON.stringify({ date, productStatusId });
        return this.axios.request({ ...localVarRequestOptions, url: this.basePath + localVarUrlObj.pathname });
    }
}
