/* tslint:disable */
/* eslint-disable */
/**
 * xxx业务应用
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 单个产品类型的月度检测统计结果
 *
 * @export
 * @interface LkProductTypeMonthlyStatOutput
 */
export interface LkProductTypeMonthlyStatOutput {

    /**
     * 产品类型ID
     *
     * @type {number}
     * @memberof LkProductTypeMonthlyStatOutput
     */
    productTypeId?: number;

    /**
     * 产品类型名称
     *
     * @type {string}
     * @memberof LkProductTypeMonthlyStatOutput
     */
    productTypeName?: string | null;

    /**
     * 统计年月，格式 yyyy-MM
     *
     * @type {string}
     * @memberof LkProductTypeMonthlyStatOutput
     */
    yearMonth?: string | null;

    /**
     * 检测总数
     *
     * @type {number}
     * @memberof LkProductTypeMonthlyStatOutput
     */
    total?: number;

    /**
     * OK 数量
     *
     * @type {number}
     * @memberof LkProductTypeMonthlyStatOutput
     */
    okCount?: number;

    /**
     * NG 数量
     *
     * @type {number}
     * @memberof LkProductTypeMonthlyStatOutput
     */
    ngCount?: number;

    /**
     * 合格率（保留4位小数，例如 0.9523 表示 95.23%）
     *
     * @type {number}
     * @memberof LkProductTypeMonthlyStatOutput
     */
    passRate?: number;
}
