/* tslint:disable */
/* eslint-disable */
/**
 * xxx业务应用
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 用户检测统计结果
 *
 * @export
 * @interface LkUserInspectionStatOutput
 */
export interface LkUserInspectionStatOutput {

    /**
     * 用户ID
     *
     * @type {number}
     * @memberof LkUserInspectionStatOutput
     */
    userId?: number;

    /**
     * 用户姓名
     *
     * @type {string}
     * @memberof LkUserInspectionStatOutput
     */
    userName?: string | null;

    /**
     * 统计日期（今日统计时有值，全量统计时为空）
     *
     * @type {string}
     * @memberof LkUserInspectionStatOutput
     */
    date?: string | null;

    /**
     * 检测总次数
     *
     * @type {number}
     * @memberof LkUserInspectionStatOutput
     */
    total?: number;

    /**
     * OK 数量
     *
     * @type {number}
     * @memberof LkUserInspectionStatOutput
     */
    okCount?: number;

    /**
     * NG 数量
     *
     * @type {number}
     * @memberof LkUserInspectionStatOutput
     */
    ngCount?: number;
}
